### ISSUE TITLE
Posible ineffective use of RL in MY-bdos.asm

### ISSUE THREAD

**Issue by radekh** [cj7hawk/LokiOS#1]
Hi,

I'm staring at your code.  On line 119 you use `RL A! AND $FE`.  That's three bytes.  Is there any reason, I overlook, why are you not using `SLA A` instead.

Anyhow, I'm playing with the same in my FDOS.ASM and I'm using following 

```
00EE2B 26 00             0093   LD      H,0             ; Compute address in BDOSTAB
00EE2D 69                0094   LD      L,C             ;+ First we load fn into HL
00EE2E 29                0095   ADD     HL,HL           ;+ Then we double it
00EE2F 11 AC EE          0096   LD      DE,BDOSTAB      ;+ Get address of the table
00EE32 19                0097   ADD     HL,DE           ;+ Sum together to get address
```

**Comment by radekh** [comment]
Sorry, it's me again

few instructions down I see de-reference of HL into DE.
```.asm
                LD              E,(hl)                          ; Move the jump vector to DE
                INC             HL
                LD              D,(hl)
                PUSH    DE                                      ; Push DE vector onto the stack so we can use RET to get there. 
                POP             HL                                      ; HL now contains the jump vector.
```

I use a "trick" to de-reference HL directly into HL.
```.lst
00EE33 7E                0099   LD      A,(HL)          ; Fetch the function address
00EE34 23                0100   INC     HL              ;+to HL
00EE35 66                0101   LD      H,(HL)          ;+
00EE36 6F                0102   LD      L,A             ;+
```
That will save you another byte, and few clocks when messing with stack.

**Comment by cj7hawk** [comment]
Hmmm. I never thought of doing that with HL - I like it. Not so much because of the saving of a few bytes, but because it doesn't require changing the DE register, although sometimes I have information in the A register as well, which I want to preserve, so I guess it's routine-specific. I'll need to recheck the routine to make sure I'm not needing to preserve A. 

But I do like the "trick" - thank you. 

It's not perfect code, and not fully optimised yet. I'm still writing the greater elements of the OS and working on the hardware side of things presently so I can shift from an emulator to physical hardware.

**Comment by cj7hawk** [comment]
While RL A and AND make a clear outcome, SLA A does the same... so I've taken on the suggestion thank you.
